spring.application.name=ecom-Application
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb

#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

project.image=images/


spring.app.jwtSecret=mySecretKey124123fsfsfsdfdsfsfdsfdsfdsfasfef
spring.app.jwtExpirationMs=36000000

spring.app.jwtCookieName=springBootEcom

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

logging.level.org.com.ecom=DEBUG

logging.level.org.springframework=INFO


