spring.application.name=ecom-Application

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb

#SQL DB configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=Nikhil@021

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#PostgreSQL DB AWS configuration
#spring.datasource.url=jdbc:postgresql://e-commerce.c6lsiuaya21l.us-east-1.rds.amazonaws.com:5432/e-commerce
#spring.datasource.username=postgres
#spring.datasource.password=Nikhil0@21

#PostgreSQL DB LOCAL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Nikhil@021

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


project.image=images/


spring.app.jwtSecret=mySecretKey124123fsfsfsdfdsfsfdsfdsfdsfasfef
spring.app.jwtExpirationMs=36000000

spring.app.jwtCookieName=springBootEcom

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

logging.level.org.com.ecom=DEBUG

logging.level.org.springframework=INFO

#elastic beanstalk
#server.port=5000


